version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5173:5173" # Porta padrão usada pelo Vite
    command: npm run dev